# Generated by Django 5.2.7 on 2025-10-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-year'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.AddField(
            model_name='book',
            name='availability_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.CharField(default='good', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='course_code',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
