# Generated by Django 5.2.7 on 2025-10-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0002_alter_book_options_remove_book_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
